spring:
  datasource:
    url: jdbc:mysql://localhost:3306/website
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations:  classpath:mapper/*.xml
  type-aliases-package: com.codecart.pojo
  configuration:
    map-underscore-to-camel-case: true
#logging:
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} ===> %msg%n"
